### PR TITLE
Update definitions for Tabris.js 1.1.0

### PR DESCRIPTION
**Pull request by cpetrov**

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks il Will see your PR next month 

Do we need to create a release after that ?

**Comment by angelozerr** [comment]
Thanks @cpetrov !

Do we need to create a new release?

**Comment by cpetrov** [comment]
Yes, thank you.

**Comment by angelozerr** [comment]
Do you think you could hav etime to do https://github.com/angelozerr/tern-tabris/issues/26 ?

**Comment by cpetrov** [comment]
I'll be available after August 21st.

**Comment by angelozerr** [comment]
> I'll be available after August 21st.

Ok, do you think is there a chance that you can work on https://github.com/angelozerr/tern-tabris/issues/26 

If no, I will create the release (for your information, I hav eintegrated your work inside tern.java)

**Comment by cpetrov** [comment]
I won't have the possibility to do this right now. Thank you for the release!

**Pull request merged**
