### PR TITLE
String autocompletion improvement

### PR DESCRIPTION
**Pull request by cpetrov**

### CODE REVIEW

**Comment by angelozerr** [comment]
Could you add a test for this new feature please. Thanks

**Comment by cpetrov** [comment]
@angelozerr I've turned this into a CodeMirror addon. To test it it'd be needed to integrate the CM test suite into the repository. Would it be a good idea to copy over "test" from CM as test/codemirror, remove the CM tests not relevant to this repository, include the suite into our tests and configure it to just run the CM tests for this addon?

**Comment by angelozerr** [comment]
For test, I mean tabris_Proxy_set that you have added

For CM, you can add tes too.

**Comment by cpetrov** [comment]
@angelozerr Thanks for your answer, I've added a test.

**Comment by angelozerr** [comment]
Thanks @cpetrov !

**Pull request merged**
